# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""
Process LLM-generated code to extract valid Python functions.

This module provides utilities for cleaning and validating LLM-generated code,
following DeepMind's FunSearch approach. LLMs often generate code wrapped in
markdown, with conversational text, or with syntax errors. These utilities
extract and validate the actual Python function from such output.
"""

import ast
import re

# ---------------------------------------------------------------------------
# GraphWranglingMethods toolkit registry
# Mirrors Funsearch/GraphWranglingMethods/__all__ — update both if functions change.
# ---------------------------------------------------------------------------
_TOOLKIT_FUNCTIONS: frozenset[str] = frozenset([
    # parsing
    "parse_atom", "break_edge", "text2edges", "build_graph", "build_simple_graph",
    # path_analysis
    "has_path", "shortest_path_length", "count_paths", "count_trails",
    "all_shortest_paths", "paths_with_relations", "graph_diameter", "eccentricity",
    # structure
    "node_degree", "get_neighbors", "get_edge_types_between", "get_all_edge_types",
    "count_edges_of_type", "num_nodes", "num_edges",
    "connected_components", "strongly_connected_components", "has_cycle",
    "betweenness_centrality", "pagerank", "in_degree_centrality", "out_degree_centrality",
])


def strip_markdown_and_text(generated_text: str) -> str:
    """
    Remove markdown code blocks and conversational text, extract just Python code.
    
    LLMs often wrap code in markdown blocks (```python ... ```) and add
    explanatory text before/after the code. This function extracts only the
    Python code portion.
    
    Args:
        generated_text (str): Raw text generated by the LLM, which may contain:
            - Markdown code fences: ```python ... ```
            - Conversational text: "Here is the function:", "Please note..."
            - Multiple code blocks
            - Mixed text and code
            
    Returns:
        str: Extracted Python code without markdown or conversational text.
             If no code is found, returns the original text unchanged.
             
    Examples:
        >>> text = '''Here is a function:
        ... ```python
        ... def priority(x):
        ...     return x * 2
        ... ```
        ... Please note this is just an example.'''
        >>> result = strip_markdown_and_text(text)
        >>> print(result)
        def priority(x):
            return x * 2
            
    Behavior:
        - Detects markdown code blocks starting with ``` and ending with ```
        - Extracts the first code block containing 'def priority'
        - If no markdown is present, returns text starting from first 'def priority'
        - Preserves all lines within the detected code block
    """
    lines = generated_text.split('\n')
    code_lines = []
    in_code_block = False
    found_function = False
    
    for i, line in enumerate(lines):
        # Check for markdown code block markers
        if line.strip().startswith('```'):
            if not in_code_block:
                # Starting a code block
                in_code_block = True
            else:
                # Ending a code block
                in_code_block = False
                if found_function:
                    # We found our function, stop here
                    break
            continue
        
        # If we're in a code block or not using markdown, collect code
        if in_code_block or not any('```' in l for l in lines):
            # Look for function definition
            if line.strip().startswith('def priority'):
                found_function = True
                in_code_block = True  # Force collection even without markdown
            
            if in_code_block and found_function:
                code_lines.append(line)
    
    # If we found nothing, return original text
    if not code_lines:
        return generated_text
    
    return '\n'.join(code_lines)


def validate_function_has_return(function_code: str) -> bool:
    """
    Validate that a function has valid Python syntax and at least one return statement.
    
    Uses Python's Abstract Syntax Tree (AST) parser to verify the code structure.
    This follows DeepMind's FunSearch approach of validating generated code before
    execution.
    
    Args:
        function_code (str): Complete Python function definition as a string.
            Must be valid Python code with 'def function_name(...): ...'
            
    Returns:
        bool: True if the function:
            - Has valid Python syntax (parses successfully)
            - Contains exactly one function definition
            - Has at least one return statement in its body
            
            False if:
            - Syntax is invalid
            - Multiple or zero function definitions found
            - No return statement present
            - Any parsing error occurs
            
    Examples:
        >>> code = '''def priority(x):
        ...     if x > 0:
        ...         return 1.0
        ...     return 0.0'''
        >>> validate_function_has_return(code)
        True
        
        >>> incomplete = '''def priority(x):
        ...     x = x + 1'''  # Missing return
        >>> validate_function_has_return(incomplete)
        False
        
    Notes:
        - Silent failure: Returns False for any exception without raising
        - Prints diagnostic message if return statement is missing
        - Used to filter out incomplete LLM generations before execution
    """
    try:
        tree = ast.parse(function_code)
        function_defs = [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
        
        if len(function_defs) != 1:
            return False
        
        func_def = function_defs[0]
        has_return = any(isinstance(node, ast.Return) for node in ast.walk(func_def))
        
        if not has_return:
            print(f"Function validation failed: no return statement found")
            return False
            
        return True
    except Exception as e:
        # Silent failure - any parsing error means invalid function
        return False


def extract_function_from_llm_output(generated_text: str) -> tuple[str, bool]:
    """
    Extract a complete, valid Python function from LLM-generated text.
    
    This is the main entry point for processing LLM output. It handles:
    1. Markdown code blocks (```python ... ```)
    2. Conversational text before/after code
    3. Multiple function definitions (takes only the first priority_v function)
    4. Validation of completeness and correct parameter order
    
    Expected parameter order for priority function:
    priority(cand_fact: str, definite_rules_program: str, entailed_facts: str, facts_program: str)
    
    Args:
        generated_text (str): Raw text output from an LLM, which may contain:
            - Markdown code blocks (```python ... ```)
            - Conversational text ("Here's a function:", etc.)
            - Multiple functions (we take first priority_v* function)
            - Comments and explanatory text
            
    Returns:
        tuple[str, bool]: A tuple containing:
            - str: The extracted function code as a string. Empty string if extraction failed.
            - bool: True if extraction succeeded and function is valid (has return statement),
                   False if extraction failed or function is incomplete.
    """
    # Step 1: Strip markdown code blocks and conversational text
    code_only = strip_markdown_and_text(generated_text)
    
    if not code_only.strip():
        print("Function extraction failed: No code found after stripping markdown")
        return '', False
    
    # Step 2: Extract just the first priority_v* function
    # LLM might generate multiple functions or extra code
    lines = code_only.split('\n')
    function_lines = []
    inside_function = False
    function_found = False
    base_indent = None
    in_docstring = False
    docstring_delimiter = None
    
    for line in lines:
        stripped = line.strip()
        
        # Look for function definition starting with 'def priority'
        if stripped.startswith('def priority'):
            if function_found:
                # We already found a function, stop here (prevent multiple functions)
                break
            inside_function = True
            function_found = True
            function_lines.append(line)
            base_indent = len(line) - len(line.lstrip())
            
            # Validate parameter order
            # Expected: cand_fact, definite_rules_program, entailed_facts, facts_program
            param_match = re.search(r'def\s+priority[_v\d]*\s*\((.*?)\)\s*->', line)
            if param_match:
                params_str = param_match.group(1)
                # Extract just parameter names (ignore type hints and spaces)
                param_names = [p.split(':')[0].strip() for p in params_str.split(',') if p.strip()]
                
                expected_order = ['cand_fact', 'definite_rules_program', 'entailed_facts', 'facts_program']
                if param_names != expected_order:
                    print(f"Warning: Parameter order mismatch. Expected {expected_order}, got {param_names}")
                    print(f"Will attempt to reorder parameters to match expected signature")
                    # Note: We'll continue and rely on the renaming step to fix this
            
            continue
        
        if not inside_function:
            continue
        
        # Track docstrings
        if not in_docstring and (stripped.startswith('"""') or stripped.startswith("'''")):
            delimiter = '"""' if stripped.startswith('"""') else "'''"
            docstring_delimiter = delimiter
            in_docstring = True
            function_lines.append(line)
            if stripped.count(delimiter) >= 2:
                in_docstring = False
                docstring_delimiter = None
            continue
        
        if in_docstring:
            function_lines.append(line)
            if docstring_delimiter in line:
                in_docstring = False
                docstring_delimiter = None
            continue
        
        # Empty lines are OK
        if not stripped:
            function_lines.append(line)
            continue
        
        # Check indentation to detect end of function
        current_indent = len(line) - len(line.lstrip())
        
        if current_indent <= base_indent and stripped:
            # End of function - check if it's explanatory text
            if stripped.startswith('#') or stripped.startswith('def ') or stripped.startswith('class '):
                break
            # Also stop at common explanatory patterns
            if any(stripped.startswith(p) for p in ['In this', 'This function', 'Note that', 'The above']):
                break
        
        # Part of function body
        function_lines.append(line)
    
    if not function_lines:
        print("Function extraction failed: No function definition found")
        return '', False
    
    result = '\n'.join(function_lines)
    
    # Rename priority_vX to priority (standardize function name)
    result = re.sub(r'\bpriority_v\d+\b', 'priority', result)
    
    # Ensure the signature matches expected order
    # Replace any incorrect parameter order with the correct one
    def_line_match = re.search(r'(def\s+priority\s*\()([^)]+)(\)\s*->.*?:)', result)
    if def_line_match:
        prefix = def_line_match.group(1)
        params = def_line_match.group(2)
        suffix = def_line_match.group(3)
        
        # Always enforce the correct signature
        correct_params = "cand_fact: str, definite_rules_program: str, entailed_facts: str, facts_program: str"
        result = result.replace(def_line_match.group(0), f"{prefix}{correct_params}{suffix}")
    
    # Step 3: Validate it has a return statement
    is_valid = validate_function_has_return(result)
    
    if not is_valid:
        print(f"Function extraction failed validation")
        print(f"Extracted code was:\n{result[:500]}...")
    
    # Step 4: Auto-inject imports for any GraphWranglingMethods functions used.
    # This removes any import the LLM may have written itself, then injects a
    # single canonical import for exactly the names that are actually called.
    if is_valid:
        used_names = detect_toolkit_usage(result)
        result = inject_toolkit_imports(result, used_names)
    
    return result, is_valid


# ---------------------------------------------------------------------------
# Toolkit import helpers
# ---------------------------------------------------------------------------

def detect_toolkit_usage(function_code: str) -> list[str]:
    """Return the sorted list of GraphWranglingMethods function names called in *function_code*.

    Method 1 (primary): AST walk — finds ``ast.Call`` nodes whose callee is a bare
    ``ast.Name`` matching a known toolkit name.  Ignores occurrences inside string
    literals or import statements.

    Method 2 (fallback): Regex scan — used when the code has a syntax error that
    prevents AST parsing.  Looks for ``toolkit_name(`` patterns.

    Args:
        function_code: Extracted Python function string.

    Returns:
        Sorted list of toolkit function names that are called, e.g.
        ``['build_simple_graph', 'has_path', 'text2edges']``.
    """
    used: set[str] = set()

    try:
        # Method 1: AST-based (precise)
        tree = ast.parse(function_code)
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Name)
                and node.func.id in _TOOLKIT_FUNCTIONS
            ):
                used.add(node.func.id)
    except SyntaxError:
        # Method 2: Regex fallback
        pattern = (
            r'\b('
            + '|'.join(re.escape(name) for name in sorted(_TOOLKIT_FUNCTIONS))
            + r')\s*\('
        )
        for m in re.finditer(pattern, function_code):
            used.add(m.group(1))

    return sorted(used)


def inject_toolkit_imports(function_code: str, used_names: list[str]) -> str:
    """Inject a ``from Funsearch.GraphWranglingMethods import ...`` line into the function.

    Any existing ``GraphWranglingMethods`` import lines anywhere in the code are
    removed first (normalising any import the LLM may have written itself).  Then
    a single import for exactly *used_names* is inserted as the first statement
    of the function body, after the ``def`` line and any opening docstring.

    Returns *function_code* unchanged when *used_names* is empty.

    Args:
        function_code: Extracted Python function string.
        used_names: Sorted list of toolkit names to import (from :func:`detect_toolkit_usage`).

    Returns:
        Function string with the import injected (or the original if nothing to inject).
    """
    if not used_names:
        return function_code

    lines = function_code.split('\n')

    # Remove any pre-existing GraphWranglingMethods import lines
    lines = [l for l in lines if 'GraphWranglingMethods' not in l]

    insert_idx = _find_body_start(lines)

    # Determine indentation from the first body line; fall back to 4 spaces
    if insert_idx < len(lines) and lines[insert_idx].strip():
        indent = ' ' * (len(lines[insert_idx]) - len(lines[insert_idx].lstrip()))
    else:
        indent = '    '

    import_line = (
        f"{indent}from Funsearch.GraphWranglingMethods import "
        + ', '.join(used_names)
    )
    lines.insert(insert_idx, import_line)
    return '\n'.join(lines)


def _find_body_start(lines: list[str]) -> int:
    """Return the index of the first non-docstring body line inside a function.

    Scans *lines* (which must start with the ``def`` line at index 0) and
    skips the ``def`` line itself plus any opening docstring, then returns the
    index of the first real statement.

    Returns ``len(lines)`` when no body is found (e.g. stub function).
    """
    in_docstring = False
    docstring_delim: str | None = None

    for i, line in enumerate(lines):
        if i == 0:
            continue  # always skip the def line

        stripped = line.strip()

        if in_docstring:
            if docstring_delim and docstring_delim in stripped:
                in_docstring = False
            continue

        if not stripped:
            continue  # skip blank lines between def and docstring / body

        # Check whether this line *opens* a docstring
        for delim in ('"""', "'''"):
            if stripped.startswith(delim):
                rest = stripped[len(delim):]  # everything after the opening delimiter
                if delim in rest:
                    # Delimiter closes on the same line → single-line docstring
                    break  # skip this line and keep looking for body start
                else:
                    # Multi-line docstring starts here
                    in_docstring = True
                    docstring_delim = delim
                    break
        else:
            # Not a docstring opener → this is the first body statement
            return i

    return len(lines)
