import os
import pickle
import argparse
from collections.abc import Sequence
from typing import Any, Dict
import sys
from torch_scatter import scatter_min
# this_dir = os.path.dirname(os.path.abspath(__file__))
# project_root = os.path.abspath(os.path.join(this_dir, '..', '..'))
# if project_root not in sys.path:
#     sys.path.insert(0, project_root)

from concurrent.futures import ProcessPoolExecutor

import torch
import pandas as pd
from torch.utils.data import DataLoader

from functools import partial
from Funsearch.Evaluator.train import parse_args, story_collate
from Funsearch.Evaluator.model import EdgeTransformer
from Funsearch.Evaluator.eval_utils import StoryDataset
from Funsearch.Collaterals.story_query_generator_nora1_1 import StoryQueryGeneratorNoRa1_1

from DeepMindCodeReference.implementation import code_manipulation
from DeepMindCodeReference.implementation import programs_database
from DeepMindCodeReference.implementation.evaluator import _sample_to_program, _calls_ancestor
from Funsearch.Collaterals.PrioStoryGeneratorNoRa1_1 import PrioStoryGeneratorNoRa1_1

PRINT_NUM_TIMES = 0

def _generate_story_and_queries_worker(
    priority_fn_str: str,
    story_idx: int,
    seed: int,
    rules_path: str,
    min_entities: int,
    max_entities: int,
    num_cands: int,
) -> pd.DataFrame:
    """Top-level worker function for parallel story generation (must be picklable).

    Converts *priority_fn_str* to a callable, generates one story, builds
    the corresponding query DataFrame, and tags it with *story_idx*.
    """
    namespace: dict = {}
    exec(priority_fn_str, namespace)
    priority_fn = namespace['priority']

    generator_story = PrioStoryGeneratorNoRa1_1(
        priority_fn=priority_fn,
        seed=seed,
        min_entities=min_entities,
        max_entities=max_entities,
        num_cands=num_cands,
    )
    story_info = generator_story.generate_story_from_rules(rules_path)

    generator_queries = StoryQueryGeneratorNoRa1_1()
    df_queries = generator_queries.build_query_dataframe(story_info)
    df_queries['story_id'] = story_idx
    return df_queries


def compute_min_correct_logprobs(logits: torch.Tensor, labels_mask: torch.Tensor) -> float:
    """
    Compute min of minimum logits for correct labels per query.

    For each query, finds the minimum logit among the correct label positions,
    then returns the min across all queries.

    Args:
        logits: Model output logits, shape (Q, num_labels)
        labels_mask: Multi-hot boolean mask of correct labels, shape (Q, num_labels)

    Returns:
        Min of minimum correct logits across queries
    """
    # Create query indices (1-indexed to distinguish from 0 which marks incorrect labels)
    # Shape: (Q, 1)
    Q = labels_mask.shape[0]
    indices = torch.arange(1, Q + 1, device=logits.device).unsqueeze(-1)

    # Multiply indices by mask: correct positions get their query index, others get 0
    # Shape: (Q, num_labels) -> ravel to (Q * num_labels,)
    index = (indices * labels_mask).ravel()

    # Flatten logits to match
    logits_flat = logits.ravel()

    # scatter_min groups by index and takes minimum
    # Index 0 collects all incorrect positions (we ignore it)
    # Indices 1..Q collect correct positions for each query
    min_correct_logits, _ = scatter_min(logits_flat, index, dim=-1)

    # min_correct_logits[0] is garbage (incorrect positions), skip it
    # Take min of min_correct_logits[1:Q+1]
    return min_correct_logits[1:Q+1].min().item()


PRINT_NUM_TIMES = 0
class EvaluatorET:
    """Class that analyses functions generated by LLMs."""

    def __init__(
        self,
        database: programs_database.ProgramsDatabase,
        template: code_manipulation.Program,
        function_to_evolve: str,
        function_to_run: str,
        inputs: Sequence[Any],
        timeout_seconds: int = 30,
        num_stories: int = 10,
        batch_size: int = 1,
        device: str = 'cuda',
        model_path: str = None,
        parallel_stories: int = 1,
    ):

        assert batch_size == 1, "Num of queries which is variable is the implicit batch dimension."
        # Future use
        self._database = database
        self._template = template
        self._function_to_evolve = function_to_evolve
        self._function_to_run = function_to_run
        self._inputs = inputs
        self._timeout_seconds = timeout_seconds

        # Setup paths and config
        self._cl_args = parse_args([])
        self._cl_args.batch_size = batch_size
        self._this_dir = os.path.dirname(os.path.abspath(__file__))

        # Load label mappings , _unique_edge_labels gives the map on how to tokenize the relationship names 
        labels_path = os.path.join(self._this_dir, 'unique_labels.pkl')
        with open(labels_path, 'rb') as f:
            self._unique_edge_labels, self._unique_query_labels = pickle.load(f)

        self._cl_args.edge_types = len(self._unique_edge_labels) + 1
        self._cl_args.target_size = len(self._unique_query_labels)

        # Load pretrained EdgeTransformer model.
        # Always deserialise to CPU first (map_location='cpu'), then move to the
        # target device.  Loading directly to 'cuda' can raise "CUDA out of memory"
        # in the main process before multiprocessing workers are spawned, even when
        # the GPU has plenty of free memory, due to CUDA context initialisation order.
        if device == 'cuda' and not torch.cuda.is_available():
            device = 'cpu'
        self._device = device
        self._model = EdgeTransformer(self._cl_args)
        if model_path is None:
            self._cl_args.exp_name = 'no_ambig_input_v2'
            model_path = os.path.join(self._this_dir, f'{self._cl_args.exp_name}.pth')
        self._model.load_state_dict(torch.load(model_path, map_location='cpu'))
        self._model.eval()
        if self._device != 'cpu':
            self._model = self._model.to(self._device)

        self._num_stories = num_stories
        self._parallel_stories = parallel_stories

    def df_to_loader(self, df_queries: pd.DataFrame) -> DataLoader:
        """Convert a query DataFrame to a DataLoader."""
        dict_df = df_queries.to_dict(orient='list')
        dataset = StoryDataset(dict_df, self._unique_edge_labels, self._unique_query_labels)
        collate_fn = partial(story_collate, num_edge_types=len(self._unique_edge_labels) + 1)
        return DataLoader(dataset, batch_size=1, shuffle=False, collate_fn=collate_fn)

    def _move_batch_to_device(self, batch: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        """Move all tensors in batch dict to the model's device.
        
        Args:
            batch: Dictionary containing tensor data
            
        Returns:
            Batch with all tensors moved to model's device
        """
        return {key: val.to(self._device) if isinstance(val, torch.Tensor) else val 
                for key, val in batch.items()}

    def _convert_string_to_priority_function(self, priority_fn_str: str):
        """Convert a priority function string into an executable function.
        
        Args:
            priority_fn_str: String containing the priority function code
            
        Returns:
            The priority function object
        """
        # Create a namespace for the function
        namespace = {}
        # Execute the string to define the function in the namespace
        exec(priority_fn_str, namespace)
        
        # Extract the priority function (assuming it's named 'priority')
        if 'priority' not in namespace:
            raise ValueError("Priority function must be named 'priority'")
        
        return namespace['priority']
    
    def _generate_single_story(
        self,
        priority_fn,
        seed: int,
        rules_path: str,
        min_entities: int = 6,
        max_entities: int = 9,
        num_cands: int = 32
    ) -> Dict[str, Any]:
        """Generate a single story using the priority function.
        
        Args:
            priority_fn: The priority function to use
            seed: Random seed for story generation
            rules_path: Path to the rules file
            min_entities: Minimum number of entities in the story
            max_entities: Maximum number of entities in the story
            num_cands: Number of candidate facts to consider
            
        Returns:
            Dictionary containing story information
        """
        generator_story = PrioStoryGeneratorNoRa1_1(
            priority_fn=priority_fn,
            seed=seed,
            min_entities=min_entities,
            max_entities=max_entities,
            num_cands=num_cands
        )
        
        story_info = generator_story.generate_story_from_rules(rules_path)
        # print(f'keys i n story info are {story_info.keys()} .')
        return story_info
    
    def _build_queries_for_story(
        self,
        story_info: Dict[str, Any],
        generator_queries: StoryQueryGeneratorNoRa1_1
    ) -> pd.DataFrame:
        """Build query dataframe for a given story.
        
        Args:
            story_info: Dictionary containing story information
            generator_queries: Query generator instance
            
        Returns:
            DataFrame containing queries for the story
        """
        df_queries = generator_queries.build_query_dataframe(story_info)
        return df_queries
    
    def _generate_stories_and_queries(
        self,
        priority_fn,
        num_stories: int = 3,
        base_seed: int = 42,
        min_entities: int = 6,
        max_entities: int = 9,
        num_cands: int = 32,
        priority_fn_str: str = None,
    ) -> pd.DataFrame:
        """Generate multiple stories and their corresponding queries.
        
        Args:
            priority_fn: The priority function to use for story generation
            num_stories: Number of stories to generate
            base_seed: Base random seed for reproducibility
            min_entities: Minimum number of entities per story
            max_entities: Maximum number of entities per story
            num_cands: Number of candidate facts to consider
            priority_fn_str: The priority function source code (needed for
                parallel generation; if None, falls back to sequential path)
            
        Returns:
            DataFrame containing all queries from all stories
        """
        rules_path = os.path.join(self._this_dir, "..", "Collaterals", "NoRa1.1.txt")

        # Compute seeds: original scheme used seed = base_seed + story_idx + int_increment
        # where int_increment == story_idx, so effective seed = base_seed + 2*story_idx
        seeds = [base_seed + 2 * idx for idx in range(num_stories)]

        # ---- parallel path ----
        if self._parallel_stories > 1 and num_stories > 1 and priority_fn_str is not None:
            dfs: list[pd.DataFrame] = []
            import multiprocessing as _mp
            mp_ctx = _mp.get_context("spawn")
            with ProcessPoolExecutor(
                max_workers=min(self._parallel_stories, num_stories),
                mp_context=mp_ctx,
            ) as pool:
                futures = [
                    pool.submit(
                        _generate_story_and_queries_worker,
                        priority_fn_str=priority_fn_str,
                        story_idx=idx,
                        seed=seeds[idx],
                        rules_path=rules_path,
                        min_entities=min_entities,
                        max_entities=max_entities,
                        num_cands=num_cands,
                    )
                    for idx in range(num_stories)
                ]
                for fut in futures:
                    dfs.append(fut.result())
            return pd.concat(dfs, ignore_index=True)

        # ---- sequential path (original logic, preserved for backward compat) ----
        generator_queries = StoryQueryGeneratorNoRa1_1()
        final_df_queries = pd.DataFrame()
        
        story_idx = 0
        int_increment = 0
        
        while story_idx < num_stories:
            story_info = self._generate_single_story(
                priority_fn=priority_fn,
                seed=base_seed + story_idx + int_increment,
                rules_path=rules_path,
                min_entities=min_entities,
                max_entities=max_entities,
                num_cands=num_cands
            )
            
            df_queries = self._build_queries_for_story(story_info, generator_queries)
            df_queries['story_id'] = story_idx
            final_df_queries = pd.concat([final_df_queries, df_queries])
            
            story_idx += 1
            int_increment += 1
        
        return final_df_queries
    
    def _evaluate_queries(self, df_queries: pd.DataFrame) -> Dict[str, float]:
        """Evaluate model on the given queries and return metrics.
        
        Args:
            df_queries: DataFrame containing queries to evaluate
            
        Returns:
            Dictionary containing evaluation metrics
        """
        eval_loader = self.df_to_loader(df_queries)

        metrics = {
            'acc': [],
            'macro_f1': [],
            'loss': [],
            'mean_min_logprobs': []
        }
        global PRINT_NUM_TIMES
        batch_num = 0
        with torch.no_grad():
            for batch in eval_loader:
                # Ensure batch is on the same device as model
                batch = self._move_batch_to_device(batch)
                loss, logits = self._model._calculate_loss(batch)
                # if PRINT_NUM_TIMES == 0:
                #     print(f''' story/batch {batch_num} shape of logits.shape: {logits.shape} and loss is: {loss} and 
                #           batch is {batch.keys()}  we have shape of target_edge_type {batch['target_edge_type'].shape}
                #              and the first elemnt of the batjhc is  {batch['target_edge_type'][0,:]} and
                #                logits for first element are {logits[0,:]}. the shape of 
                #                {batch['target_edge_index'].shape} and the first element is {batch['target_edge_index'][0:]}''') 
                batch_num += 1
                    # PRINT_NUM_TIMES += 1
                acc, macro_f1, micro_f1 = self._model.compute_acc(batch, logits)##shape of logits is (B, num_rels)
                # Compute mean of minimum logits for correct labels per query
                labels_mask = batch['target_edge_type'].to(torch.bool)
                mean_min_logprobs = compute_min_correct_logprobs(logits, labels_mask)
                metrics['mean_min_logprobs'].append(mean_min_logprobs)
                metrics['acc'].append(acc.item())
                metrics['macro_f1'].append(macro_f1)
                metrics['loss'].append(loss.item())
        # print(f'the log_probs for different stories are {metrics["mean_min_logprobs"]}')
        return metrics

    def analyse(
        self,
        priority_fn_str: str = None,
        df_queries: pd.DataFrame = None,
        num_stories: int = None,
        base_seed: int = 42,
        min_entities: int = 6,
        max_entities: int = 9,
        num_cands: int = 22
    ) -> Dict[str, float]:
        """Main analysis method that generates stories/queries and evaluates them.
        
        This method can work in two modes:
        1. Generate mode: Provide priority_fn_str to generate stories and queries
        2. Direct evaluation mode: Provide df_queries to directly evaluate
        
        Args:
            priority_fn_str: String containing the priority function code
            df_queries: Pre-generated queries DataFrame (if not generating new ones)
            num_stories: Number of stories to generate (uses instance default if None)
            base_seed: Base random seed for story generation
            min_entities: Minimum number of entities per story
            max_entities: Maximum number of entities per story
            num_cands: Number of candidate facts to consider
            
        Returns:
            Dictionary containing evaluation metrics
        """
        global PRINT_NUM_TIMES
        # Use instance defaults if not provided
        if num_stories is None:
            num_stories = self._num_stories
        
        # Determine which mode to use
        if df_queries is None:
            # Generate mode: need to generate stories and queries
            if priority_fn_str is None:
                raise ValueError("Either priority_fn_str or df_queries must be provided")
            
            # Convert string to function
            priority_fn = self._convert_string_to_priority_function(priority_fn_str)
            
            # Generate stories and queries
            df_queries = self._generate_stories_and_queries(
                priority_fn=priority_fn,
                num_stories=num_stories,
                base_seed=base_seed,
                min_entities=min_entities,
                max_entities=max_entities,
                num_cands=num_cands,
                priority_fn_str=priority_fn_str,
            )
            # if PRINT_NUM_TIMES == 0:
            #     print(f"Generated {len(df_queries)} queries with columns {df_queries.columns}. the number of stories is {num_stories}.")
                # PRINT_NUM_TIMES += 1
        # Evaluate the queries
        metrics = self._evaluate_queries(df_queries)
        
        return metrics

    def _future_analyse(
        self,
        sample: str = None,
        island_id: int | None = None,
        version_generated: int | None = None,
    ) -> None:
        """TODO: Keeping this here as reference for the future.
        
        Compiles the sample into a program and executes it on test inputs.
        """
        new_function, program = _sample_to_program(
            sample, version_generated, self._template, self._function_to_evolve
        )

        scores_per_test = {}
        for current_input in self._inputs:
            test_output, runs_ok = self._sandbox.run(
                program, self._function_to_run, current_input, self._timeout_seconds
            )
            if (runs_ok and not _calls_ancestor(program, self._function_to_evolve)
                    and test_output is not None):
                if not isinstance(test_output, (int, float)):
                    raise ValueError('@function.run did not return an int/float score.')
                scores_per_test[current_input] = test_output

        if scores_per_test:
            self._database.register_program(new_function, island_id, scores_per_test)



if __name__ == "__main__":
    # Define the priority function as a string (as would come from FunSearch)
    priority_fn_str = """
def priority(cand_fact: str, definite_rules_program: str, entailed_facts: str, facts_program: str) -> float:
    '''
    Priority function for selecting among candidate facts.

    Inputs:
      - cand_fact: candidate fact string, e.g. "father_of(1,3)."
      - definite_rules_program: string containing all definite (Horn) rules
      - entailed_facts: string containing facts in the stable model that are not in story facts or candidate facts
      - facts_program: string containing all ground facts

    FunSearch should evolve this function.
    '''
    return 0.0
"""
    ## test =============================================EvaluatorET
    print("="*60)
    print("Starting Evaluator Test Run")
    print("="*60)
    
    # Configuration
    num_stories = 3
    
    # evaluator = EvaluatorET(
    #     database=None,
    #     template=None,
    #     function_to_evolve=None,
    #     function_to_run=None,
    #     inputs=None,
    #     num_stories=num_stories,
    # )
    
    # # Run analysis with the priority function
    # print(f"\nRunning analyze with priority function...")
    # print(f"  - base_seed: 42")
    # print(f"  - min_entities: 6")
    # print(f"  - max_entities: 9")
    # print(f"  - num_cands: 22")
    
    # metrics = evaluator.analyse(
    #     priority_fn_str=priority_fn_str,
    #     num_stories=num_stories,
    #     base_seed=42,
    #     min_entities=6,
    #     max_entities=9,
    #     num_cands=3
    # )
    
    # # Display results
    # print("\n" + "="*60)
    # print("EVALUATION RESULTS")
    # print("="*60)
    # print(f' method returned {metrics["mean_min_logprobs"]}')
    # print(f' method returned {metrics["acc"]}')
    # for metric_name, values in metrics.items():
    #     if values:
    #         avg_value = sum(values) / len(values)
    #         print(f"{metric_name:20s}: {avg_value:.4f} (avg over {len(values)} stories/batches)")
    #     else:
    #         print(f"{metric_name:20s}: No data")
    
    # Display results
    print("\n" + "="*60)
    print("EVALUATION RESULTS")
    print("="*60)
    print(f' method returned {metrics["mean_min_logprobs"]}')
    print(f' method returned {metrics["acc"]}')
    for metric_name, values in metrics.items():
        if values:
            avg_value = sum(values) / len(values)
            print(f"{metric_name:20s}: {avg_value:.4f} (avg over {len(values)} stories/batches)")
        else:
            print(f"{metric_name:20s}: No data")
    
    print("="*60)
    #### test ============================================= compute_min_correct_logprobs
    # logits = torch.tensor([
    #     [2.0, -1.0, 5.0],    # query 0
    #     [0.5, 3.0, -2.0],    # query 1
    # ])

    # labels_mask = torch.tensor([
    #     [1, 1, 0],   # query 0: labels 0 and 1 are correct
    #     [0, 1, 1],   # query 1: labels 1 and 2 are correct
    # ], dtype=torch.bool)

    # print("Logits:")
    # print(logits)
    # print("\nLabels mask:")
    # print(labels_mask)

    # result = compute_min_correct_logprobs(logits, labels_mask)

    # # Manually computed expectations:
    # # Query 0 correct logits: [2.0, -1.0] → min = -1.0
    # # Query 1 correct logits: [3.0, -2.0] → min = -2.0
    # # Mean = (-1.0 + -2.0) / 2 = -1.5
    # expected = min(-1.0, -2.0)

    # print("\nComputed result:", result)
    # print("Expected result:", expected)

    # assert abs(result - expected) < 1e-6

